language: minimal

services: docker

install:
  - docker-compose -f docker-compose-build.yaml build --parallel
# Scripts to be run such as tests
before_script:
  - echo "no tests"
# Build
# Tagging
script:
  - docker --version 
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed "$DOCKER_HUB"/udagram-api-feed:v1

  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy "$DOCKER_HUB"/udagram-reverseproxy:v1

  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user "$DOCKER_HUB"/udagram-api-user:v1

  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend "$DOCKER_HUB"/udagram-frontend:v1
# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_HUB"//udagram-api-feed:v1
  - docker push "$DOCKER_HUB"/udagram-reverseproxy:v1
  - docker push "$DOCKER_HUB"/udagram-api-user:v1
  - docker push "$DOCKER_HUB"/udagram-frontend:v1